"""add_assignment_submissions_quiz_attempts_and_cohort_lesson_fields

Revision ID: dbafd43e2a02
Revises: f7bb609eaf41
Create Date: 2026-09-19 01:08:33.987840
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbafd43e2a02'
down_revision: Union[str, None] = 'f7bb609eaf41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_submissions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('submission_url', sa.String(length=2048), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'GRADED', 'RESUBMISSION_REQUESTED', name='submissionstatus'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('graded_by_id', sa.Uuid(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['graded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_submissions_enrollment_id'), 'assignment_submissions', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_assignment_submissions_lesson_id'), 'assignment_submissions', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_assignment_submissions_user_id'), 'assignment_submissions', ['user_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('answers_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_enrollment_id'), 'quiz_attempts', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_lesson_id'), 'quiz_attempts', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.add_column('cohorts', sa.Column('meeting_url', sa.String(length=2048), nullable=True))
    op.add_column('cohorts', sa.Column('meeting_passcode', sa.String(length=100), nullable=True))
    op.add_column('cohorts', sa.Column('schedule_info', sa.String(length=500), nullable=True))
    op.add_column('cohorts', sa.Column('announcement', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('attachments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'attachments')
    op.drop_column('cohorts', 'announcement')
    op.drop_column('cohorts', 'schedule_info')
    op.drop_column('cohorts', 'meeting_passcode')
    op.drop_column('cohorts', 'meeting_url')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_lesson_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_enrollment_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_assignment_submissions_user_id'), table_name='assignment_submissions')
    op.drop_index(op.f('ix_assignment_submissions_lesson_id'), table_name='assignment_submissions')
    op.drop_index(op.f('ix_assignment_submissions_enrollment_id'), table_name='assignment_submissions')
    op.drop_table('assignment_submissions')
    # ### end Alembic commands ###
